### ISSUE TITLE
Users Page

### ISSUE THREAD

**Issue by kent1313** [kent1313/VBS-Project#16]
The users page is not complete at all! So far, the users page is just a copy of an old version of the "kidConfiguration" page.

**Comment by kent1313** [comment]
The user page is looking nice, but we need a way to add users in the interface, add it could still use some improvement elsewhere.

**Comment by kent1313** [comment]
I think we should make a way for an administrator to edit a user's profile before we release the software to other churches' VBS

**Comment by digitaleagle** [comment]
It saves now.  It doesn't load the user when the leader is selected from the group

**Comment by digitaleagle** [comment]
I believe this is all working now with the latest pull
